CREATE DATABASE Library;

USE Library;

CREATE TABLE Book (
    EntryID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Genre VARCHAR(100) NOT NULL,
    PublicationDate DATE NOT NULL,
    ISBN VARCHAR(13) UNIQUE NOT NULL
);
